//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KullanicilerEntities3 : DbContext
    {
        public KullanicilerEntities3()
            : base("name=KullanicilerEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kisiler> Kisiler { get; set; }
        public virtual DbSet<OkulBlg> OkulBlg { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
