//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public Nullable<int> SoruId { get; set; }
        public Nullable<int> CevapId { get; set; }
        public string AnketId { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
    }
}
